<?php
require_once 'config.php';
requireRole('tester');

// Get filter parameters
$status = $_GET['status'] ?? 'all';
$priority = $_GET['priority'] ?? 'all';
$dateFrom = $_GET['date_from'] ?? '';
$dateTo = $_GET['date_to'] ?? '';
$projectId = $_GET['project_id'] ?? 'all';
$developerId = $_GET['developer_id'] ?? 'all';
$testerId = $_GET['tester_id'] ?? 'all';

// Build query
$whereClause = "WHERE bt.created_by = ?";
$params = [$_SESSION['user_id']];

if ($status !== 'all') {
    $whereClause .= " AND bt.status = ?";
    $params[] = $status;
}

if ($priority !== 'all') {
    $whereClause .= " AND bt.priority = ?";
    $params[] = $priority;
}

if (!empty($dateFrom)) {
    $whereClause .= " AND DATE(bt.created_at) >= ?";
    $params[] = $dateFrom;
}

if (!empty($dateTo)) {
    $whereClause .= " AND DATE(bt.created_at) <= ?";
    $params[] = $dateTo;
}
if ($projectId !== 'all') {
    $whereClause .= $whereClause ? " AND bt.project_id = ?" : " WHERE bt.project_id = ?";
    $params[] = $projectId;
}

if ($developerId !== 'all') {
    $whereClause .= $whereClause ? " AND bt.assigned_dev_id = ?" : " WHERE bt.assigned_dev_id = ?";
    $params[] = $developerId;
}

if ($testerId !== 'all') {
    $whereClause .= $whereClause ? " AND bt.created_by = ?" : " WHERE bt.created_by = ?";
    $params[] = $testerId;
}
// Get projects for filter dropdown
$projects = [];
try {
    $stmt = $pdo->query("SELECT id, name FROM projects ORDER BY name");
    $projects = $stmt->fetchAll();
} catch (PDOException $e) {
    $error = 'Failed to fetch projects: ' . $e->getMessage();
}

// Get developers and testers for filter dropdowns
$developers = [];
$testers = [];
try {
    $stmt = $pdo->query("SELECT id, name FROM users WHERE role = 'developer' ORDER BY name");
    $developers = $stmt->fetchAll();
    $stmt = $pdo->query("SELECT id, name FROM users WHERE role = 'tester' ORDER BY name");
    $testers = $stmt->fetchAll();
} catch (PDOException $e) {
    $error = 'Failed to fetch users: ' . $e->getMessage();
}

// Get selected project name for PDF header
$selectedProjectName = 'All Projects';
if ($projectId !== 'all') {
    foreach ($projects as $project) {
        if ($project['id'] == $projectId) {
            $selectedProjectName = $project['name'];
            break;
        }
    }
}

// Get bugs for report
$bugs = [];
$totalBugs = 0;
$stats = [
    'pending' => 0,
    'in_progress' => 0,
    'fixed' => 0,
    'approved' => 0,
    'rejected' => 0
];

try {
    // Get bugs with creator and developer names
    $stmt = $pdo->prepare("
        SELECT bt.*, 
               u1.name as developer_name,
               u2.name as creator_name
        FROM bug_tickets bt 
        LEFT JOIN users u1 ON bt.assigned_dev_id = u1.id 
        LEFT JOIN users u2 ON bt.created_by = u2.id 
        $whereClause 
        ORDER BY bt.id ASC
    ");
    $stmt->execute($params);
    $bugs = $stmt->fetchAll();
    $totalBugs = count($bugs);
    
    // Calculate stats
    foreach ($bugs as $bug) {
        $stats[$bug['status']]++;
    }
} catch (PDOException $e) {
    $error = 'Failed to generate report';
}

// Handle CSV generation
if (isset($_GET['download']) && $_GET['download'] == 'csv') {
    // Set headers for CSV download
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="bug_report_' . date('Y-m-d') . '.csv"');
    header('Cache-Control: no-cache, no-store, must-revalidate');
    header('Pragma: no-cache');
    header('Expires: 0');

    // Generate CSV content
    $output = fopen('php://output', 'w');

    // Write summary section
    fputcsv($output, ['BUG TRACKING REPORT']);
    fputcsv($output, ['Generated by', $_SESSION['user_name']]);
    fputcsv($output, ['Date', date('F d, Y')]);
    fputcsv($output, []); // Empty row
    fputcsv($output, ['SUMMARY']);
    fputcsv($output, ['Total Bugs', count($bugs)]);
    fputcsv($output, ['Approved', $stats['approved']]);
    fputcsv($output, ['In Progress', $stats['pending'] + $stats['in_progress']]);
    fputcsv($output, ['Rejected', $stats['rejected']]);
    fputcsv($output, []); // Empty row

    // Write bug details header
    fputcsv($output, ['BUG DETAILS']);
    fputcsv($output, [
        'Bug ID', 
        'Date of Creation', 
        'Module', 
        'Submodule', 
        'Developer', 
        'Bug Title', 
        'Bug Description', 
        'Created By', 
        'Bug Priority', 
        'Status', 
        'Updated On'
    ]);

    // Write bug details
    foreach ($bugs as $bug) {
        fputcsv($output, [
            '#' . $bug['id'],
            date('M d, Y', strtotime($bug['created_at'])),
            $bug['module'] ?: 'N/A',
            $bug['submodule'] ?: 'N/A',
            $bug['developer_name'] ?: 'Unassigned',
            $bug['title'],
            substr($bug['description'], 0, 200) . (strlen($bug['description']) > 200 ? '...' : ''),
            $bug['creator_name'] ?: 'Unknown',
            $bug['priority'],
            ucfirst(str_replace('_', ' ', $bug['status'])),
            date('M d, Y', strtotime($bug['updated_at']))
        ]);
    }

    fclose($output);
    exit();
}

// Handle PDF (HTML) generation
if (isset($_GET['download']) && $_GET['download'] == 'pdf') {
    // Generate HTML content for PDF
    $htmlContent = generatePDFContent($bugs, $stats, $_SESSION['user_name']);
    
    // Set headers for HTML download (for PDF conversion)
    header('Content-Type: text/html; charset=utf-8');
    header('Content-Disposition: attachment; filename="bug_report_' . date('Y-m-d') . '.html"');
    
    echo $htmlContent;
    exit();
}

function generatePDFContent($bugs, $stats, $userName) {
    ob_start();
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <title>Bug Report</title>
        <link rel="icon" href="logo.ico" type="image/x-icon">
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { text-align: center; margin-bottom: 30px; }
            .stats { display: flex; justify-content: space-around; margin-bottom: 30px; }
            .stat-item { text-align: center; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th, td { border: 1px solid #ddd; padding: 6px; text-align: left; font-size: 0.75rem; line-height: 1.2; }
            th { background-color: #f2f2f2; }
            .priority-p1 { background-color: #ef4444; }
            .priority-p2 { background-color: #f97316; }
            .priority-p3 { background-color: #eab308; }
            .priority-p4 { background-color: #22c55e; }
        </style>
        <link rel="icon" href="logo.ico" type="image/x-icon">
    </head>
    <body>
        <div class="header">
            <h1>Bug Tracking Report</h1>
            <p>Generated by: <?php echo htmlspecialchars($userName); ?></p>
            <p>Date: <?php echo date('F d, Y'); ?></p>
        </div>
        
        <div class="stats">
            <div class="stat-item">
                <h3><?php echo count($bugs); ?></h3>
                <p>Total Bugs</p>
            </div>
            <div class="stat-item">
                <h3><?php echo $stats['approved']; ?></h3>
                <p>Resolved</p>
            </div>
            <div class="stat-item">
                <h3><?php echo $stats['pending'] + $stats['in_progress']; ?></h3>
                <p>In Progress</p>
            </div>
            <div class="stat-item">
                <h3><?php echo $stats['rejected']; ?></h3>
                <p>Rejected</p>
            </div>
        </div>
        
        <table>
            <thead>
                <tr>
                    <th>Bug ID</th>
                    <th>Date of Creation</th>
                    <th>Module</th>
                    <th>Submodule</th>
                    <th>Developer</th>
                    <th>Bug Title</th>
                    <th>Bug Description</th>
                    <th>Created By</th>
                    <th>Bug Priority</th>
                    <th>Status</th>
                    <th>Updated On</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($bugs as $bug): ?>
                <tr class="priority-<?php echo strtolower($bug['priority']); ?>">
                    <td>#<?php echo $bug['id']; ?></td>
                    <td><?php echo date('M d, Y', strtotime($bug['created_at'])); ?></td>
                    <td><?php echo htmlspecialchars($bug['module'] ?: 'N/A'); ?></td>
                    <td><?php echo htmlspecialchars($bug['submodule'] ?: 'N/A'); ?></td>
                    <td><?php echo $bug['developer_name'] ? htmlspecialchars($bug['developer_name']) : 'Unassigned'; ?></td>
                    <td><?php echo htmlspecialchars($bug['title']); ?></td>
                    <td><?php echo htmlspecialchars(substr($bug['description'], 0, 200) . (strlen($bug['description']) > 200 ? '...' : '')); ?></td>
                    <td><?php echo $bug['creator_name'] ? htmlspecialchars($bug['creator_name']) : 'Unknown'; ?></td>
                    <td><?php echo $bug['priority']; ?></td>
                    <td><?php echo ucfirst(str_replace('_', ' ', $bug['status'])); ?></td>
                    <td><?php echo date('M d, Y', strtotime($bug['updated_at'])); ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </body>
    </html>
    <?php
    return ob_get_clean();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generate Report - <?php echo SITE_NAME; ?></title>
    <script>
        (function() {
            const savedTheme = localStorage.getItem('theme') || 'light';
            document.documentElement.setAttribute('data-theme', savedTheme);
        })();
    </script>
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="app-container">
        <?php include 'includes/navbar.php'; ?>

        <main class="main-content">
            <div class="page-header">
                <h1>Bug Report Generator</h1>
                <p>Generate comprehensive reports of your bug tracking activity</p>
            </div>

            <div class="report-container">
                <div class="report-filters">
                    <h3>Report Filters</h3>
                    <form method="GET" class="filter-form">
                        <div class="form-row">
                            <div class="form-group">
                                <label for="status">Status</label>
                                <select id="status" name="status">
                                    <option value="all" <?php echo ($status == 'all') ? 'selected' : ''; ?>>All Status</option>
                                    <option value="pending" <?php echo ($status == 'pending') ? 'selected' : ''; ?>>Pending</option>
                                    <option value="in_progress" <?php echo ($status == 'in_progress') ? 'selected' : ''; ?>>In Progress</option>
                                    <option value="fixed" <?php echo ($status == 'fixed') ? 'selected' : ''; ?>>Fixed</option>
                                    <option value="approved" <?php echo ($status == 'approved') ? 'selected' : ''; ?>>Approved</option>
                                    <option value="rejected" <?php echo ($status == 'rejected') ? 'selected' : ''; ?>>Rejected</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="priority">Priority</label>
                                <select id="priority" name="priority">
                                    <option value="all" <?php echo ($priority == 'all') ? 'selected' : ''; ?>>All Priorities</option>
                                    <option value="P1" <?php echo ($priority == 'P1') ? 'selected' : ''; ?>>P1 - Critical</option>
                                    <option value="P2" <?php echo ($priority == 'P2') ? 'selected' : ''; ?>>P2 - High</option>
                                    <option value="P3" <?php echo ($priority == 'P3') ? 'selected' : ''; ?>>P3 - Medium</option>
                                    <option value="P4" <?php echo ($priority == 'P4') ? 'selected' : ''; ?>>P4 - Low</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="project_id">Project</label>
                                <select id="project_id" name="project_id">
                                    <option value="all" <?php echo ($projectId == 'all') ? 'selected' : ''; ?>>All Projects</option>
                                    <?php foreach ($projects as $project): ?>
                                        <option value="<?php echo $project['id']; ?>" <?php echo ($projectId == $project['id']) ? 'selected' : ''; ?>>
                                            <?php echo htmlspecialchars($project['name']); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label for="developer_id">Developer</label>
                                <select id="developer_id" name="developer_id">
                                    <option value="all" <?php echo ($developerId == 'all') ? 'selected' : ''; ?>>All Developers</option>
                                    <?php foreach ($developers as $developer): ?>
                                        <option value="<?php echo $developer['id']; ?>" <?php echo ($developerId == $developer['id']) ? 'selected' : ''; ?>>
                                            <?php echo htmlspecialchars($developer['name']); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="tester_id">Tester</label>
                                <select id="tester_id" name="tester_id">
                                    <option value="all" <?php echo ($testerId == 'all') ? 'selected' : ''; ?>>All Testers</option>
                                    <?php foreach ($testers as $tester): ?>
                                        <option value="<?php echo $tester['id']; ?>" <?php echo ($testerId == $tester['id']) ? 'selected' : ''; ?>>
                                            <?php echo htmlspecialchars($tester['name']); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="date_from">From Date</label>
                                <input type="date" id="date_from" name="date_from" value="<?php echo htmlspecialchars($dateFrom); ?>">
                            </div>

                            <div class="form-group">
                                <label for="date_to">To Date</label>
                                <input type="date" id="date_to" name="date_to" value="<?php echo htmlspecialchars($dateTo); ?>">
                            </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">
                                <span>🔍</span> Generate Report
                            </button>
                            <button type="button" onclick="clearFilters()" class="btn btn-outline">Clear Filters</button>
                        </div>
                    </form>
                </div>

                <?php if (!empty($bugs)): ?>
                    <div class="report-summary">
                        <h3>Report Summary</h3>
                        <div class="stats-grid">
                            <div class="stat-card">
                                <div class="stat-icon">📊</div>
                                <div class="stat-content">
                                    <h3><?php echo $totalBugs; ?></h3>
                                    <p>Total Bugs</p>
                                </div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-icon">⏳</div>
                                <div class="stat-content">
                                    <h3><?php echo $stats['pending'] + $stats['in_progress']; ?></h3>
                                    <p>In Progress</p>
                                </div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-icon">✅</div>
                                <div class="stat-content">
                                    <h3><?php echo $stats['approved']; ?></h3>
                                    <p>Resolved</p>
                                </div>
                            </div>
                            <div class="stat-card">
                                <div class="stat-icon">❌</div>
                                <div class="stat-content">
                                    <h3><?php echo $stats['rejected']; ?></h3>
                                    <p>Rejected</p>
                                </div>
                            </div>
                        </div>

                        <div class="report-actions">
                            <a href="?<?php echo http_build_query(array_merge($_GET, ['download' => 'pdf'])); ?>" class="btn btn-primary">
                                <span>📄</span> Download PDF Report
                            </a>
                            <a href="?<?php echo http_build_query(array_merge($_GET, ['download' => 'csv'])); ?>" class="btn btn-primary">
                                <span>📊</span> Download CSV Report
                            </a>
                            <button onclick="window.print()" class="btn btn-outline">
                                <span>🖨️</span> Print Report
                            </button>
                        </div>
                    </div>

                    <div class="report-table">
                        <h3>Bug Details</h3>
                        <div class="table-container">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Bug ID</th>
                                        <th>Date of Creation</th>
                                        <th>Module</th>
                                        <th>Submodule</th>
                                        <th>Developer</th>
                                        <th>Bug Title</th>
                                        <th>Bug Description</th>
                                        <th>Created By</th>
                                        <th>Bug Priority</th>
                                        <th>Status</th>
                                        <th>Updated On</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($bugs as $bug): ?>
                                        <tr>
                                            <td>#<?php echo $bug['id']; ?></td>
                                            <td><?php echo date('M d, Y', strtotime($bug['created_at'])); ?></td>
                                            <td><?php echo htmlspecialchars($bug['module'] ?: 'N/A'); ?></td>
                                            <td><?php echo htmlspecialchars($bug['submodule'] ?: 'N/A'); ?></td>
                                            <td><?php echo $bug['developer_name'] ? htmlspecialchars($bug['developer_name']) : 'Unassigned'; ?></td>
                                            <td><?php echo htmlspecialchars($bug['title']); ?></td>
                                            <td><?php echo htmlspecialchars(substr($bug['description'], 0, 200) . (strlen($bug['description']) > 200 ? '...' : '')); ?></td>
                                            <td><?php echo $bug['creator_name'] ? htmlspecialchars($bug['creator_name']) : 'Unknown'; ?></td>
                                            <td>
                                                <span class="priority-badge" style="background-color: <?php echo getPriorityColor($bug['priority']); ?>">
                                                    <?php echo $bug['priority']; ?>
                                                </span>
                                            </td>
                                            <td>
                                                <span class="status-badge" style="background-color: <?php echo getStatusColor($bug['status']); ?>">
                                                    <?php echo ucfirst(str_replace('_', ' ', $bug['status'])); ?>
                                                </span>
                                            </td>
                                            <td><?php echo date('M d, Y', strtotime($bug['updated_at'])); ?></td>
                                            <td>
                                                <a href="view_bug.php?id=<?php echo $bug['id']; ?>" class="btn btn-outline btn-small">View</a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="empty-state">
                        <div class="empty-icon">📊</div>
                        <h3>No bugs found</h3>
                        <p>No bugs match your current filter criteria. Try adjusting the filters above.</p>
                    </div>
                <?php endif; ?>
            </div>
        </main>
    </div>

    <script>
        function clearFilters() {
            window.location.href = 'generate_report.php';
        }
    </script>

    <style>
          <style>
        /* Compact Professional CSS Variables */
        :root {
            --primary-color: #3b82f6;
            --primary-hover: #2563eb;
            --success-color: #10b981;
            --warning-color: #f59e0b;
            --error-color: #ef4444;
            --background-color: #f8fafc;
            --surface-color: #ffffff;
            --text-primary: #1e293b;
            --text-secondary: #64748b;
            --border-color: #e2e8f0;
            --border-radius: 6px;
            --box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }

        [data-theme="dark"] {
            --primary-color: #60a5fa;
            --success-color: #34d399;
            --warning-color: #fbbf24;
            --error-color: #f87171;
            --background-color: #0f172a;
            --surface-color: #1e293b;
            --text-primary: #f1f5f9;
            --text-secondary: #cbd5e1;
            --border-color: #334155;
            --box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
        }

        /* Smooth transitions */
        * { transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease; }

        /* Main Layout - Compact */
        .report-container {
            display: grid;
            gap: 1.5rem;
            max-width: 100%;
        }

        /* Filters Section - Compact */
        .report-filters {
            background: var(--surface-color);
            padding: 1.5rem;
            border-radius: var(--border-radius);
            box-shadow: var(--box-shadow);
            border: 1px solid var(--border-color);
        }

        .report-filters h3 {
            margin-bottom: 1rem;
            color: var(--text-primary);
            font-weight: 600;
            font-size: 1.1rem;
        }

        .filter-form { display: grid; gap: 1rem; }

        .form-row {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 0.75rem;
        }

        .form-group { display: flex; flex-direction: column; }

        .form-group label {
            margin-bottom: 0.25rem;
            font-weight: 500;
            color: var(--text-primary);
            font-size: 0.875rem;
        }

        .form-group select,
        .form-group input {
            padding: 0.5rem;
            border: 1px solid var(--border-color);
            border-radius: var(--border-radius);
            background: var(--surface-color);
            color: var(--text-primary);
            font-size: 0.875rem;
            transition: border-color 0.3s ease;
        }

        .form-group select:focus,
        .form-group input:focus {
            outline: none;
            border-color: var(--primary-color);
            box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.1);
        }

        .form-actions {
            display: flex;
            gap: 0.75rem;
            margin-top: 0.75rem;
            flex-wrap: wrap;
        }

        /* Compact Button Styles */
        .btn {
            display: inline-flex;
            align-items: center;
            gap: 0.375rem;
            padding: 0.5rem 1rem;
            border-radius: var(--border-radius);
            font-weight: 500;
            text-decoration: none;
            cursor: pointer;
            transition: all 0.3s ease;
            font-size: 0.875rem;
            border: 1px solid;
        }

        .btn-primary {
            background: var(--primary-color);
            color: white;
            border-color: var(--primary-color);
        }

        .btn-primary:hover {
            background: var(--primary-hover);
            transform: translateY(-1px);
        }

        .btn-outline {
            background: transparent;
            color: var(--text-primary);
            border-color: var(--border-color);
        }

        .btn-outline:hover {
            background: var(--background-color);
            border-color: var(--primary-color);
            color: var(--primary-color);
        }

        .btn-small { padding: 0.25rem 0.5rem; font-size: 0.75rem; }

        /* Summary Section - Compact */
        .report-summary {
            background: var(--surface-color);
            padding: 1.5rem;
            border-radius: var(--border-radius);
            box-shadow: var(--box-shadow);
            border: 1px solid var(--border-color);
        }

        .report-summary h3 {
            margin-bottom: 1rem;
            color: var(--text-primary);
            font-weight: 600;
            font-size: 1.1rem;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 1rem;
            margin-bottom: 1.5rem;
        }

        .stat-card {
            background: var(--background-color);
            padding: 1rem;
            border-radius: var(--border-radius);
            box-shadow: var(--box-shadow);
            display: flex;
            align-items: center;
            gap: 0.75rem;
            border: 1px solid var(--border-color);
        }

        .stat-icon {
            font-size: 1.5rem;
            width: 40px;
            height: 40px;
            background: var(--surface-color);
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            border: 1px solid var(--border-color);
            flex-shrink: 0;
        }

        .stat-content h3 {
            font-size: 1.5rem;
            font-weight: 700;
            color: var(--text-primary);
            margin-bottom: 0.125rem;
            line-height: 1;
        }

        .stat-content p {
            color: var(--text-secondary);
            font-size: 0.8rem;
            margin: 0;
        }

        .report-actions {
            display: flex;
            gap: 0.75rem;
            margin-top: 1.5rem;
            flex-wrap: wrap;
        }

        /* Compact Table Section */
        .report-table {
            background: var(--surface-color);
            padding: 1.5rem;
            border-radius: var(--border-radius);
            box-shadow: var(--box-shadow);
            border: 1px solid var(--border-color);
        }

        .report-table h3 {
            margin-bottom: 1rem;
            color: var(--text-primary);
            font-weight: 600;
            font-size: 1.1rem;
        }

        .table-container {
            overflow: auto;
            border-radius: var(--border-radius);
            border: 1px solid var(--border-color);
            max-height: 500px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            background: var(--surface-color);
            min-width: 900px;
        }

        th, td {
            padding: 0.5rem 0.375rem;
            text-align: left;
            border-right: 1px solid var(--border-color);
            font-size: 0.75rem;
            line-height: 1.2;
            vertical-align: top;
        }

        th:last-child, td:last-child { border-right: none; }

        th {
            font-weight: 600;
            color: var(--text-primary);
            background: var(--background-color);
            position: sticky;
            top: 0;
            z-index: 10;
            border-bottom: 2px solid var(--border-color);
        }

        td {
            color: var(--text-secondary);
            border-bottom: 1px solid var(--border-color);
        }

        tbody tr:hover { background: var(--background-color); }

        /* Compact Column Widths */
        th:nth-child(1), td:nth-child(1) { width: 60px; }
        th:nth-child(2), td:nth-child(2) { width: 80px; }
        th:nth-child(3), td:nth-child(3) { width: 70px; }
        th:nth-child(4), td:nth-child(4) { width: 70px; }
        th:nth-child(5), td:nth-child(5) { width: 90px; }
        th:nth-child(6), td:nth-child(6) { width: 150px; }
        th:nth-child(7), td:nth-child(7) { width: 180px; }
        th:nth-child(8), td:nth-child(8) { width: 80px; }
        th:nth-child(9), td:nth-child(9) { width: 60px; }
        th:nth-child(10), td:nth-child(10) { width: 70px; }
        th:nth-child(11), td:nth-child(11) { width: 80px; }
        th:nth-child(12), td:nth-child(12) { width: 60px; }

        /* Badge Styles - Compact */
        .priority-badge, .status-badge {
            display: inline-block;
            padding: 0.125rem 0.375rem;
            border-radius: 10px;
            color: #fff;
            font-weight: 500;
            font-size: 0.7rem;
            white-space: nowrap;
        }

        /* Empty State */
        .empty-state {
            text-align: center;
            padding: 3rem 1.5rem;
            background: var(--surface-color);
            border-radius: var(--border-radius);
            box-shadow: var(--box-shadow);
            border: 1px solid var(--border-color);
            color: var(--text-secondary);
        }

        .empty-icon { font-size: 3rem; margin-bottom: 0.75rem; }
        .empty-state h3 { font-size: 1.25rem; margin-bottom: 0.75rem; color: var(--text-primary); }

        /* Scrollbar - Compact */
        .table-container::-webkit-scrollbar { width: 6px; height: 6px; }
        .table-container::-webkit-scrollbar-track { background: var(--surface-color); }
        .table-container::-webkit-scrollbar-thumb { background: var(--border-color); border-radius: 3px; }

        /* Responsive - Mobile First */
        @media (max-width: 768px) {
            .form-row { grid-template-columns: 1fr; }
            .stats-grid { grid-template-columns: 1fr 1fr; gap: 0.75rem; }
            .report-filters, .report-summary, .report-table { padding: 1rem; }
            .form-actions, .report-actions { flex-direction: column; }
            th, td { padding: 0.375rem 0.25rem; font-size: 0.7rem; }
            .stat-card { padding: 0.75rem; }
            .stat-icon { width: 35px; height: 35px; font-size: 1.25rem; }
        }

        @media (max-width: 480px) {
            .stats-grid { grid-template-columns: 1fr; }
            .btn { width: 100%; justify-content: center; }
            th, td { padding: 0.25rem; font-size: 0.65rem; }
        }

        /* Print Styles */
        @media print {
            .navbar, .page-header, .report-filters, .report-actions { display: none !important; }
            .main-content { padding: 0; max-width: none; }
            .report-container { gap: 1rem; }
            .report-summary, .report-table { 
                background: white !important; 
                color: black !important; 
                box-shadow: none !important; 
                border: 1px solid #000 !important; 
            }
            th, td { color: black !important; border-color: #000 !important; }
            th { background: #f0f0f0 !important; }
        }
</style>

</body>
</html>